### ISSUE TITLE
Basic CTI functionality

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#379]
To provide a basic structure to work on, it should be the first milestone to create all the basic CTI functionalities.
This includes as a brief overview:
- [x] Start a campaign
- [x] Save/Load of parameters
- [x] Save/Load of sector ownership
- [x] Save/Load of elite vehicle connections
- [x] Intro and deployment cinematic
- [x] Spawn/Respawn of players
- [x] Startvehicle spawn
- [ ] FOB deployment via start box
- [ ] Change ownership of a sector
- [ ] Win campaign when condition X (e.g. all capitals in blufor ownership) is true
- [ ] End campaign with automatic save wipe.

This would fulfill a "working CTI mission" very basically. Without any enemies or nice stuff, of course.

So it would be working in the matter of *starting*, *capturing* and *winning*. With this basic functionality given, we can implement all the other Liberation features step by step (module per module) to this already working CTI mission.

The first things for this epic are "reuploads" of already finished code. Reason is, that we can rebuild a better history for this refactoring.
