### ISSUE TITLE
CBA based features implemention / Refactoring / Code cleanup

### ISSUE THREAD

**Issue by veteran29** [KillahPotatoes/KP-Liberation#467]
### Short Summary

Move existing functionalities to CBA where applicable.
Refactor existing code base if needed.

### Description

As we want to streamline further development by using CBA we need to refactor existing features to be based on CBA functions where applicable.

Also as the code base is steadily growing we need to take a small step back and take a look at the whole project to check if any parts of the code will not slow down further development.

### Sub-Tasks

- [x] Replace KP Events 
- [x] Move persistent loops to unscheduled (where applicable, have performance in mind)
- [x] Refactor Action Manager
- [x] Replace custom "namespaces" implementation
