### ISSUE TITLE
Building Camera pt.3

### ISSUE THREAD

**Issue by veteran29** [KillahPotatoes/KP-Liberation#470]
### Short Summary
Zeus like functionalities for building camera. Mainly abilities to manipulate objects in 3D space by dragging them around via cursor.

### Description
-

### Sub-Tasks
- [x] Fixed camera zoom when scrolling the items list
- [x] "Queue" of items that will be built
    - [x] Place "Ghosted" object via click on the ground
    - [x] Object can be dragged
    - [x] Object can be removed
    - [x] Object can be rotated
    - [x] Build all "ghost" objects

### TODO: 
- [ ] Object collision detection 
- [ ] Align objects to surface
- [ ] Show objects target position bounding box (like zeus)
- [ ] Allow to place objects on surfaces like roofs
- [ ] Add icons for dragging (like zeus)
- [ ] Info about current FOB~~ (scraped until resources are implemented)
    - [ ] Resources info (stub for now)
    - [ ] FOB Name
- [ ] Stub methods for resource integration~~ (scraped until resources are implemented)
- [ ] Allow to build only in FOB area 
- [ ] Close camera when player unit dies 
- [ ] Fix boats spawning at bottom of water containers
