### ISSUE TITLE
Module/Mission Initialization Overhaul

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#479]
### Short Summary
As developer/contributor I want to have an easy and reliable way to implement new features, so that I've to edit as less files as possible of the existing framework to add my enhancements.

### Description
The current implementation of the mission initialization is not that bad, but still needs too much places to "register a module":
* https://github.com/KillahPotatoes/KP-Liberation/blob/v0.97/Missionframework/init.sqf#L36
* https://github.com/KillahPotatoes/KP-Liberation/blob/v0.97/Missionframework/KPLIB_functions.hpp#L16
* https://github.com/KillahPotatoes/KP-Liberation/blob/v0.97/Missionframework/KPLIB_ui.hpp

The functions and ui hpp files can't be eliminated, but the entries in the init.sqf could be replaced with a postInit attribute for a "init function" for each module. Maybe we can expand this in a later stage to a "auto registering" of available modules, but for now we should eliminate the init.sqf dependency for modules.
Also a closer look of the current initServer, initPlayerLocal and init could be a good idea. We should get rid of all these `waitUntil`s (especially in the init.sqf) in the end.

### Sub-Tasks
- [x] Create initialization functions for each module
- [x] Remove the current initialization calls in the init.sqf
- [x] Implement the functions as postInit functions in the module functions library
- [x] Have a look for a possibility to improve the mission initialization
- [x] Share research results and/or implement the possible tweaks

**Comment by Wyqer** [comment]
This is kind of connected to the refactoring / overhaul we'll do in #467
