### ISSUE TITLE
CI Configuration

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#480]
### Short Summary
As developer/contributor I want to be sure that my contributed code in a pull request don't contain critical syntax errors, so that I can ensure that my contribution isn't breaking anything and that I haven't overlooked something critical in my own review.

### Description
To make PR reviews easier, we should implement CI as syntax check for pull requests.
Personally I've just set it up on KP Ranks as very basic method: 
https://github.com/KillahPotatoes/KP-Ranks/blob/master/.travis.yml

The goal should be that it doesn't check every single commit, but that it should check pull requests automatically and recheck the PR, when a new commit was pushed to it.

### Sub-Tasks
- [ ] Get more familiar with the possibilities of CI concerning the configuration of the behaviour
- [x] Implement the above requirements in the config file for the repo
- [x] Test the config in the task branch, if it works like intended

**Comment by Wyqer** [comment]
Just as additional info: This is an example how a check looks like in the current KP Ranks minimal configuration
https://github.com/KillahPotatoes/KP-Ranks/pull/9/checks

**Comment by bux** [comment]
You could take a look at the ACE3 CI configuration for CircleCI:
https://github.com/acemod/ACE3/blob/master/circle.yml
