### ISSUE TITLE
Event based save/load

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#502]
### Short Summary
As contributor/developer I want to be able to add saving and loading functions for a new module via event, so that there is no need to edit an existing file.

### Description
We've the goal to make modules as independent as possible from code from outside the module. Saving and loading is currently still something which would need to be written in the save function. Creating a save/load event where someone can just add the modules save/load function would be a much better way for a real module based structure. So we'll implement a CBA event and add handlers in each module.
The handler will be called in the order of the time they've been added and it'll always wait for the handlers to be finished, before the script continues. So the plan is to fire an event, all modules which added a handler will collect the save data in an array and the main save function will write the data in the profile at the end. We have to see how performant this will be in a later stage, when we've much more data to save.

### Sub-Tasks
- [x] Add CBA events for save and load
- [x] Refactor the current load and save function to fire the event instead of calling functions
- [x] Refactor the module functions for save and load to be added as eventHandler
