### ISSUE TITLE
Build System pt. 4

### ISSUE THREAD

**Issue by veteran29** [KillahPotatoes/KP-Liberation#507]
### Short Summary 
Related to #470 

As a player I want to easily build bases in similar manner that I would do this with zeus. The build system should not allow to build objects inside of each other or outside of FOB area. 

### Sub-Tasks

- [x] Align objects to surface
- [x] Show objects target position ~~bounding box (like zeus)~~, changed to show icon at target area
- [x] Allow to place objects on surfaces like roofs
- [x] Add icons for dragging (like zeus)
- [x] Allow to build only in FOB area 
- [x] Fix boats spawning at bottom of water containers
- [x] Object persistence

### ToDo Later:
- [ ] Info about current FOB
    - [ ] Resources info (stub for now)
    - [ ] FOB Name
- [ ] Show if there is enough resources to build item
- [ ] Do not allow to build if not enough resources
- [ ] Consume resources when building
- [ ] Object collision detection
- [ ] Single item build confirm
- [ ] Close camera when player unit dies

**Comment by Pi123263** [comment]
So about the ''The build system should not allow to build objects inside of each other'' part, I think that might cause some problems with buildable objects that have weird hitboxes and as an example placing stationary weapons inside bunkers

**Comment by veteran29** [comment]
Yeah sure that is valid concern, I dont know if you if have already played with this system but arma bounding boxes are a lot bigger than real models. I think it would be reasonable to provide this option as an safeguard toggle button when you don't want to blow up anything ;)

**Comment by AxeriusNetwork** [comment]
You could have an option to enable/disable the "collision"/hitboxes.
