### ISSUE TITLE
v0.97.0 Wiki/Documentation/Website

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#508]
### Short Summary
As player/contributor/developer I would like to have a place where I can read information about the mission mechanics, modules and functions without the need to ask people about it.

### Description
As the amount of code is growing, we should start to write down basic information concerning how the mission works, how each module is working, how to basically add a new module, which functions are provided, etc.

~~If we start now~~ If we would've started and ~~extend~~ extended it in every following sprint, we ~~keep~~ would've kept the needed workload small for the documentation and we ~~don't~~ wouldn't have to recap old code to write proper information about it.

So we will write down the mentioned information and also thinking about adding flowcharts for each module as visual aid to understand how it works internally.

We need to discuss, if we keep it in the GitHub Wiki pages or if we create a small website for it, which get's auto generated content via file headers and markdown files from the repository.

### Sub-Tasks
- [ ] General structure of the framework
- [ ] Module information via readme and Wiki/Website
    - [ ] Init
    - [ ] Common
    - [ ] Core
    - [ ] Persistance
    - [ ] Respawn
    - [ ] Admin
    - [ ] Resources
    - [ ] Permission
    - [ ] Arsenal
    - [ ] Player menu
    - [ ] Virtual
    - [ ] Build
    - [ ] Garrison
    - [ ] Logistic
    - [ ] Enemy
    - [ ] Cratefiller
- [ ] Functions library (for public functions)
    - [ ] Optional: Examples for each function
- [x] ~~Flowcharts for the whole mission and for the modules seperately~~ Maybe in a later stage
- [ ] Instructions how to add a module from scratch via the provided example module
- [ ] Our basic coding conventions/contribution guidelines for the public
- [x] ~~New Devkit and Tutorial~~ Will be added when we're near completion of 0.97.0
- [ ] *More stuff which will be added*
