### ISSUE TITLE
Garrison module pt. 1

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#511]
### Short Summary
As enemy I want to have a persistent garrison on sectors which spawn when players are near, so that I can fend off these ugly blufor guys.

### Description
First part for the garrison module which will provide a persistent enemy or blufor garrison at sectors.
So it won't always spawn a fresh amount of enemies upon sector activation like in the old framework. If a sector e.g. starts with 2 infantry squads, 3 cars and 2 armored vehicles and you destroy one car and one armored vehicle, then leave the sector for deactivation and you come back, you'll face 2 infantry squads, 2 cars and 1 armored vehicle.
This is also the basement for the later "enemy reinforcement" system, which will reinforce sectors with units for the garrison, not only when the sector is under attack.
For the first part of this module the goals are quite simple and basic.

### Sub-Tasks
- [x] Create garrison module structure
- [x] Testing different approaches how to save the units (points, classnames and counts, hash, etc.)
- [x] Implement save/load functionality for garrisons
    - [x] Implement an initialization of garrisons on a fresh campaign in the load function
- [x] Spawn of the garrison upon sector activation
- [x] Despawn of the garrison and saving of it's unit count/type upon sector deactivation
