### ISSUE TITLE
Remove the common sub-module in the core module

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#512]
### Short Summary
As developer I would like to have a one level module structure without sub-modules, so that I don't need to explain or accept exceptions.

### Description
In the core module we've currently a sub category of `common functions` which are defined as:

Liberation specific replacements of normal script commands, which should always be used instead of the single command.

This [common sub-module](https://github.com/KillahPotatoes/KP-Liberation/tree/v0.97S6/Missionframework/modules/01_core/fnc/common) should be moved one level higher to keep our planned one level module structure.

### Sub-Tasks
- [x] Create a module `common` or a similar speaking name
- [x] Move the current `common functions` to this module
- [x] Adjust all references and includes accordingly
