### ISSUE TITLE
Config/Parameters/Settings Overhaul

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#514]
### Short Summary
As developer I want to provide a sensible and easy settings/parameter system for not critical adjustments for the mission, so that players have an easy and intuitive way to individualize their game experience with the mission.

### Description
We'll delete all current paramters in the v0.97 version. Reason is, that it's currently a copy from the old framework parameters and therefore nearly all aren't even used yet. We'll add parameters during the development to have a cleaner set of settings.
Due to the modular structure we'll also evaluate different approaches and test them before choosing one of the following possibilities to implement these settings:
* Use the [mission parameters](https://community.bistudio.com/wiki/Arma_3_Mission_Parameters) with an own save/load functionality like it's implemented in the old framework. So every module could add own settings via includes
* Use [CBA Settings](https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System) completely. This way modules could add settings via preInit functions to the mission. Only downside would be that you have to start the mission once to set the settings you want. You could even need to restart/wipe once after you've chosen your settings, if they contain settings which affects the basic mission initialization
* Use only the [KPLIB Config File](https://github.com/KillahPotatoes/KP-Liberation/blob/v0.97S7/Missionframework/KPLIB_config.sqf) for all available settings. This way the settings need to be set by editing the file, which makes them persistent without any further work. Downside would be that players need to edit the missionfile to have the settings they like and edits could result in mistakes

We'll discuss and test the above possibilities internally but we would also appreciate opinions from everyone else on this topic. Many thanks in advance for your feedback on this.

### Sub-Tasks
- [x] Remove all unused parameters
- [x] Evaluate which implementation to use for the future settings/parameters
- [x] Implement all currently needed/used settings
- [x] ~~Start a wiki article for parameters explanations~~ Directly in the settings files
- [x] ~~Adjust the wiki article for module adding accordingly~~ Will be done until moved to gh-pages
