### ISSUE TITLE
Refactor Function Headers

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#515]
### Short Summary
As developer I want to see a functions parameter(s) and return values in the tooltip in my IDE in a proper way, so that I don't need to look some missing details up in the function file.

### Description
As we're working with VS Code and the excellent [SQF Linter](https://github.com/SkaceKamen/vscode-sqflint) from @SkaceKamen (many thanks for your great work), we've encountered that the tooltips of our own functions are not properly displayed by using our current function header template, which is based on the [BI format](https://community.bistudio.com/wiki/Functions_Library_(Arma_3)#Arguments).
As a good overview in our IDE is fortunate, we'll refactor all function headers (at least the parameter(s) section) to the template which is [suggested by CBA](https://github.com/CBATeam/CBA_A3/wiki/Documenting-SQF-functions#formatting)

Small example of the difference (first -> suggested format by CBA, second -> BI based format):
![functiondoc](https://user-images.githubusercontent.com/3811977/47259112-a6ec5a80-d4a5-11e8-9049-b0b2e30565bc.png)

### Sub-Tasks
- [x] Refactor all function headers accordingly
- [x] Refactor all param arrays
- [x] Update the *psioniq File Header* template

**Comment by Wyqer** [comment]
Not to see in the screenshot above, but the spaces should match.
```
_variable     - description lorem ipsum bla bla bla    [DATATYPE, defaults to defaultvalue]
_variable2    - description lorem ipsum                [DATATYPE, defaults to defaultvalue]
```
Just as additional clarification

Also the params array should always be as precise as possible
so not something like
```
params ["_var1", "_var2"];
```
but
```
params [
    ["_var1", [0, 0, 0], [[]], 3], // ARRAY with exactly 3 elements (like for a position with sensible default)
    ["_var2", "", [""]],           // STRING with empty string as default
    ["_var3", true, [false]],      // BOOL with true as default
    ["_var4", objNull, [objNull]]  // OBJECT with objNull as default
];
```
Comments just as explanation in this example, not to apply in the files itself.
