### ISSUE TITLE
Scripted curator management

### ISSUE THREAD

**Issue by veteran29** [KillahPotatoes/KP-Liberation#517]
### Short Summary
As an player/server administrator I want to be able to enable/disable full zeus functionality easily.

### Description
Zeus module should be moved from `mission.sqm` to separate framework module. Features available to zeus should depend on parameters/settings selected when mission was started.

### Sub-Tasks
- [x] Remove curator modules from mission file
- [x] Create `zeus` module in liberation framework
    - [x] Curator module creation via scripts
    - [x] Curator features dependent on CBA settings 
      - [x] Full curator mode
      - [x] Limited with free camera movement
      - [x] Limited with locked camera
      - [x] No curator
