### ISSUE TITLE
Universal unit preset template

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#522]
### Short Summary
As a developer I want to easily change/address the different sides unit arrays without looking up any specific things to remember, so that I could for example make selection of units for a certain event easily dynamic concerning sides which are involved.

### Description
Currently the opfor and player force presets are very different from each other. It would be very handy if they only differ in a specific keyword.

Example:
Currently it's `KPLIB_preset_airVeh` for blufor and `KPLIB_preset_oChoppers` for the enemy.
It would be more handy to have `KPLIB_preset_pChoppers` and `KPLIB_preset_eChoppers` or similar (p - player, e - enemy) so you could easily get the right variable with something like e.g.:

```
private _side = ["p", "e"] select KPLIB_isTheEnemyTheBadGuyInThisEvent;
private _choppers = missionNamespace getVariable ("KPLIB_preset_" + _side + "Choppers");
```

In my opinion this would provide a easier to modify structure. Only "downside" is that the player preset always needs the costs for certain vehicles, if we don't implement some "automatic calculation" through unit type, special abilities and available weapons (which could be something to think of later).

Also something like this should be moved to the corresponding module which uses it:
https://github.com/KillahPotatoes/KP-Liberation/blob/v0.97/Missionframework/modules/00_init/fnc/fn_init_loadPresets.sqf#L249

So I requesting for comments/opinions, if there are any.

### Sub-Tasks
- [x] Create a new universal preset template
- [ ] Change the current 0.97 presets format to the new template
- [x] ~~Adjust preset loading accordingly~~
- [x] ~~Make sure all present preset references in current codebase are adjusted~~
- [x] ~~Improve preset loading by at least removing every "module specific" information like a build tab list~~

*Striked Sub-Tasks are postponed to the next sprints, as it needs adjustments at many places in already written code, especially in the build module. This needs to be done step by step to migrate everything to the new preset template.*

**Comment by Wyqer** [comment]
Striked Sub-Tasks are postponed to the next sprints, as it needs adjustments at many places in already written code, especially in the build module. This needs to be done step by step to migrate everything to the new preset template.
