### ISSUE TITLE
 Build System pt. 5

### ISSUE THREAD

**Issue by veteran29** [KillahPotatoes/KP-Liberation#523]
### Short Summary
Related to #507

As a player I want to be able to move the items that I've already built. As I player want the camera to close when my character dies. 

As a developer I want to have an API that allows me open "single item build"

### Sub-Tasks
- [x] Close camera when player unit dies
- [x] Add an api for "single item build"
- [x] Movement of placed objects
- [x] Build FOB via "single item build"

### Nice to have
- [ ] Items categories as dropdown
- [ ] API to add buildable items/categories
- [ ] Items searchbar
