### ISSUE TITLE
Arsenal implementation

### ISSUE THREAD

**Issue by Dubjunk** [KillahPotatoes/KP-Liberation#526]
### Short Summary
As a player i want to be able to access the arsenal during the running mission, so that i can get my job on the battlefield done.

### Description
Currently the only way to load arsenal presets is the spawn menu, players aren't able to access the arsenal without using the `Redeploy` function. Additionally there will be the option to use the ACE arsenal instead of the BI arsenal (assuming ACE is enabled).

There will also be a fully redesigned arsenal dialog.

### Sub-Tasks
- [x] Implement the "arsenal" module into the framework
- [x] Redesign the arsenal dialog
- [x] Add player actions to access the dialog
- [x] Fast load of created arsenal presets
- [x] Access the arsenal
- [x] Add a CBA setting to choose between BI and ACE arsenal
- [x] Provide the feature to copy loadouts from near players
- [x] Arsenal filtering, whitelist/blacklist
- [x] Set default loadout
