### ISSUE TITLE
Civilian population

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#527]
### Short Summary
As a player I want to see some civilian activity in cities and reactive behavior of the population to my actions, so that the environment doesn't look and feel so empty and boring.

### Description
A basic spawning/controlling module for civilian presence on the map.
The behavior of the civilians in the old framework was also not overall immersive when they just run around a sector, dodging a rocket which flies over their head to the next tank next to they beloved grocery store in town. But personally I guess it's maybe not really possible to let the civilian AI behave "more natural/sensible" concerning surrounding firefights or dangers. Or it would at least a disproportionately amount of work. But we'll have a look at it, of course.

### Sub-Tasks
- [ ] Civilians spawning at sectors
- [ ] Roaming/Traveling civilians between sectors
- [ ] Evaluate possibilities to implement sensible behavior of civilians due to near battles/firefights, etc.

**Comment by fnadde42** [comment]
I just wanted to add one thing (not big enough for its own issue) but we played on the latest version (last Friday) trying to not hit the civilians and enemy aircraft (OPFOR) [bombed us to hell and destroyed 6 houses and the villagers blamed us and gave us bad rep for it](https://cdn.discordapp.com/attachments/348548428663619585/519261280494813194/20181203213533_1f.jpg).

Wouldn't it make more sense if villagers blamed OPFOR if they were the ones who bombed the place? Might be a thing to take into consideration but no biggie if the thing with rebuilding houses will be available.

**Comment by Wyqer** [comment]
It's exactly right to comment here instead of opening a new issue, so don't worry. So well done. 👍 

Concerning your comment itself:
Technically it's (at least as far as I know) not possible to really record who destroyed a building. It's indeed different if it's a building or a vehicle/unit, which has the killed/hit eventhandler. But I have a new research on this already on the list, maybe I come up with something new as I've also learned new things in the past months/years.

So in the old framework it's "sensible explained" with:
The civilians blame blufor as they are basically the ones who said "We come for the rescue, liberate you and bring you nice democracy". So if they wouldn't have started this nice operation, the civilians wouldn't have any war going on in their region and therefore nothing would've been destroyed. If blufor is able to "free" towns without collateral damage, it's a clean operation which the civilians won't judge.

**Comment by fnadde42** [comment]
That was actually something I was thinking about. From the standpoint of a civilian previously ruled by a dictator without bombs dropping in the village they mostly see the war coming as BLUFOR comes to town so in a way it would make sense to blame them. "If you were not here none of this would have happened". If this were the case, this would be nice information to have in the in-game tutorial.

We just found it quite a bit hard to liberate a town and gaining 5% without *one* villager getting hit (as they were running around all crazy in the middle of a firefight) entirely negating the gains of freeing the village but you have already addressed that in your first post.

Thanks for continuing to develop Liberation!
