### ISSUE TITLE
Resistance Forces

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#528]
### Short Summary
As a player I want to see the civilians react to my actions also with forming resistance forces, so that my actions concerning the civilian population have a noticeable impact.

### Description
Like already in the old framework, we should have again the resistance forces, which grow during the campaign. Depending on the players civilian reputation they'll fight against or alongside the players. Personally I would say that they never be allied with the enemy, so it would be a kind of:

* Now the battle has begun on our island, so we stand up and fight against both to be fully independent

or

* The friendly forces are really taking care of our land, so let's raise volunteers to help them with their efforts.

This could and will obviously change during the campaign maybe once or even often, depending on the actions and behavior of the players concerning the civilians.

In the old framework the resistance already had tiers concerning their effectiveness and gear. It raised, when resistance events happened and resistance fighters came back alive.
This resistance strength value should also be adjustable by more aspects. Thinking of side missions (bad or good, depending on your standing) for the players like bring them gear, destroy their weapon caches, help them stealing a convoy or some other stuff we'll have to think about.
The first task would indeed be the pure implementation of the background functionalities and a basic "appearance" like it's now provided in the old framework.

Also it'll make sure the players still have some work with IEDs and anything other asymmetric warfare stuff.

### Sub-Tasks
- [ ] Resistance strength value
- [ ] Functions to access/change the values accordingly with adjustment of faction enemy states
- [ ] Resistance gear in tears or similar, depending on the strength
- [ ] Events which the resistance forces involved (ambushes, support on attacks, etc.)
- [ ] Asymmetric Warfare aspects like IEDs, road blocks, etc.
- [ ] Preparations for later side missions involving the resistance forces
