### ISSUE TITLE
Enemy Commander pt1

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#529]
### Short Summary
As enemy I want to be capable of issuing strategical decisions and actions, so that I'm able to provide the players an immersive campaign.

### Description
Many of these earlier written thoughts will be in our planning and considered individually:
https://github.com/KillahPotatoes/KP-Liberation/issues/329#issuecomment-362052191

Basically the enemy needs at first some values concerning his strength, aggressiveness/awareness.
First one is to determine how many soldiers/materiel he's able to throw against the players.
The second one would be how much he sees a threat in the players action, so it'll grow during the campaign.
The sector garrisons are currently provide a very basic "enemy" for the players as a local or tactical threat. For the strategical aspect the enemy should also, depending on the players progress in certain areas, try to reinforce these sectors with additional manpower for their garrison. This by moving vehicles/soldiers from one sector to another or by reinforcing them from his military bases (which could be considered as enemy forces spawn points). All of this maybe (if the AI would be really reliable enough concerning driving skills) as real driving convoys, so that players can have opportunities to intercept them, etc. It should provide many possibilities for a much deeper experience in the future.

Providing the above foundation would be the content of this pt1.

In the next part(s) there should be the functionality, that the enemy commander evaluate possibilities for sensible counter attacks to recapture sectors or destroy player FOBs to weaken their presence in areas of the map.

Also dynamic reactions/handling of events like activated/captured/deactivated sectors would be content of the next iteration of this module.

### Sub-Tasks
- [x] Implement sensible values for the enemy capabilities
- [x] Create functions to alter these values
- [x] Create a basic foundation for further event handling
- [x] Provide a functionality to transfer garrison units from one sector to another
- [x] Provide a functionality to create new enemy units at military bases and use them as reinforcements

**Comment by EvilSh4d0w** [comment]
I find your idea already very interesting and I am curious how you will realize that.
Personally, I've been toying with the idea whether it wouldn't be interesting and useful to include a small PVP aspect.
I got stuck with interesting, sure for one or the other but probably not for all, that it is or will be meaningful I doubt rather, because it is already a big intervention in the normal game wise of Liberation. 
But to add it as an optional feature if you encounter an advocate I think it shouldn't hurt and you will see who uses it and who doesn't.
The idea behind it was to have a Opfor commander ( Restrict Zeus and smaller build menu than the Bluefors ) and maybe 4 to 6 playable units with a whitelist and then selected players on the Opfor side can support and disturb the advance of the Bluefor players or push them back.

**Comment by Pi123263** [comment]
I think having a small player group on the enemy side in the same way that Antistasi does it could be interesting, but I'm not sure how many possibilities should be included.
But it would certainly be interesting to have the enemy group be able to actually place the FOB's (which could then be used for the secondary objectives) and other similar features.

**Comment by EvilSh4d0w** [comment]
so i haven't played antistasi yet. but i think we're talking about the same possibilities in my idea, it's really just that you can interfere with the progress of the bluefor players or even push them back. 
Because if we are honest the ki is straw stupid in many cases they often react very late or not at all so that the player goes partially upright to the AO and switches off the opponent quite comfortably without this also only reacts, therefore also the proposal with a commander ( zeus ) to bring the enemy side there then directly intervene and support can but not necessarily needed. so i wouldn't use this variant as the main component so that e.g. the FOBs were built by them and created then the site mission or the AI without their commander does not do anything anymore because that would then it would be no more liberation. what would surely be more interesting, i think, would be the possibility to regain sectors and perhaps still fasten or strengthen them. and all that optional and no must so that it is not forced to use this and you can adapt to your server community easily and quickly.

**Comment by bikerocker** [comment]
If there must be players on the OPFOR team, then I believe they should only be able to spawn into the battle by taking control of an AI that's currently deployed in a sector or reinforcement wave.

These players would have to be severely limited. OPFOR has a massive advantage already because of their huge numbers and constant stream of reinforcements on the later difficulties. The AI can sometimes be exceptionally proactive, taking several sectors at a time if unchallenged. Besides this, Arsenal should be an automatic no-go, and they should only be able to take vehicles by hijacking them from OPFOR AI in a sector.

Such a system would be highly controversial. Fighting against swarms of enemies is something Liberation does better than any mission in Arma. To sacrifice that just so a few players could drive a tank out of the AO, wait for a battle to start, and then come up behind the players and blast them away, or hijack an artillery piece and simply turn them to meat paste, would be far from popular. We would need special blacklists just for what vehicles OPFOR players are allowed to commandeer. A whole new framework would have to be built on top of Liberation to make this work fairly.

In the meantime, you could just install Achilles locally on a Zeus player, have him convert a few players to OPFOR, and drop them down in enemy sectors when it's time to defend them. And this might just work out better, for 60 seconds of Zeus work, than what might be 100 hours or more of work for the developers.
