### ISSUE TITLE
Side missions framework

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#530]
### Short Summary
As a player commander I want to be able to start side missions to achieve certain effects, so that players will have a more exciting and diverse experience during the campaign.

### Description
Same as in the old framework we'll implement side missions.
In this approach we should also focus on creating something which makes it easy for us and others to implement more side missions. So it'll be a kind of "side missions framework", if possible.

### Sub-Tasks
- [x] Basic side mission framework
- [x] Functions to add side missions dynamically
- [x] Provide a template for adding side missions as sqf files
- [x] Dialog for side missions starting etc.

**Comment by EvilSh4d0w** [comment]
in the current version some possibilities are missing there are for example too few possibilities to increase the mood of the civilians again there would be e.g. missions like delivering relief supplies possibly behind hold the used relief supplies should however also cost the own resources. possibly still include IDAP in such things.

Otherwise there have been such words on our server like a mixture between Liberation and Patrolops would probably be good I think a kind of patrolops as side mission would be nice

**Comment by EvilSh4d0w** [comment]
I don't know if this fits so well here because it also has a connection to many other modules. I don't know if it is already possible or if it would be possible at all.

I've never played antistasie before, but a lot of our players talk about it and ask if we can integrate one or the other in the current version of Liberation like for example:

that the sectors are no longer displayed in color and so you don't know exactly who owns the sector, so you have to patrol regularly where maybe on the way you could happen one or the other. 

that one comes on the patrols (depends on the Civilian reputation) also direct contact with the civilians comes and possible thus a side mission starts which can be that they ask for food or medicine where to procure those the own resources costs, or that zb civilians of the opponent were held captive or kidnapped around as forced laborers somewhere to end or on the black market to be sold or or or or.

I think you can connect that to your side mission system to build in your own stuff, there would be a lot of variations you can come up with.

many say in this context also (can also be that it is now already possible) that it disturbs the opponents indirectly on the map are displayed (the square red areas) and some players then behave accordingly.
