### ISSUE TITLE
POWs and Intel Points

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#531]
### Short Summary
As a player I want to be able to capture surrendering enemies to gain intel from then, so that I can get a kind of advantage due to the available intel.

### Description
With heavy losses on their side or an overwhelming attack group in an enemy sector there should be the chance that enemy soldiers or even vehicle crews surrender.
These POWs should, like in the old framework, be brought back to a FOB for interrogations.
This will gain intel points, the planned currency for side missions in Liberation.

### Sub-Tasks
- [x] Implementation of the intel points (or similar wording) value
- [x] Chance for enemies to surrender under sensible circumstances
- [x] Event handling of surrendering enemies by providing capture actions (or ziptie with ACE), so the player can bring them to a FOB
- [x] Gaining of intel from the interrogation and also maybe chances to fire an additional event
