### ISSUE TITLE
Resources module

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#532]
### Short Summary
As a developer I want to have one module which provides all functionalities concerning the handling of resources/points, so that I don't have to rely on many other modules for further implementations.

### Description
The resource module will provide an additional strategical layer for the mission beside of just painting the map in your color.
The current thought is to extend the main resource module in comparison to the resource system from the old framework. This would mean that it doesn't just manage the three main resources (supplies, ammo, fuel) but also all other "currency like" values in the game like intel points and what else which could come in our mind.
So basically the module itself will provide the save/load of these values and corresponding functions to access/change these values. The just virtual values like intel points will be just stored as numbers in the save, while the physical resource crates should (current state) also be fully handled by this module.
This way we've just one place to let future modules communicate with concerning an kind of resource/currency. And therefore only one place which would need adjustments if we need to add some kind of resource/currency in the later development.

### Sub-Tasks
- [x] Create module in accordance to the module templates
- [x] Implement physical and virtual resource handling
- [x] Implement save/load functionalities
- [x] Provide all needed functions to ensure an easy communication with this module
