### ISSUE TITLE
Logistic Station

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#533]
### Short Summary
As a player I want to have a sensible place where I've access to logistical features like repair/rearm/refuel/salvage/etc., so that there are no global actions and weird civilian workshop buildings for these things anymore.

### Description
The following "logistic features" should be bound to one building. Like in the old framework with the salvage depot to recycle stuff.
* Recycle/Salvage
* Repair
* Rearm
* Refuel
* AI logistic convois
* Maybe some kind of logistic paradrop feature
* Adjusted [KP Cratefiller Script](https://github.com/KillahPotatoes/dubjunks-scripts) from @Dubjunk 

It would be a building you've to build for resources to get these "enhanced gameplay functionalities". Considered for this is the following, which is also a nice replacement in the old framework for the civilian workshop, if you want to change the classname for it in your version accordingly.

![logstation](https://user-images.githubusercontent.com/3811977/48658867-3ce5b780-ea49-11e8-9c6f-a436ee532317.png)
Land_RepairDepot_01_tan_F

Basic concept would be the action on the object to open the logistic menu. There you'll have (like in the admin menu) a list of functionalities (Recycle/Salvage, Resupply, Logistic, Cratefiller). Clicking on one of them will open the corresponding dialog for this feature. This also means no unrealiable recycle action on the specific vehicle anymore which needs to be attached/detached if the vehicle is near a FOB, etc.

### Sub-Tasks
- [x] Add building to the preset
- [x] Create "Choice menu"
- [x] Create Resupply Dialog
- [x] Create Recycle Dialog
- [ ] Create AI Logistics dialog (this will maybe moved to an own task)
- [ ] Implement KP Cratefiller with needed adjustements
- [x] Evaluate if there is a possibility to provide a kind of "addLogisticMenuOption" function which adds a button on the list, so other modules could provide their functionalities from the logistic menu.

**Comment by Takahashi-Yuuki** [comment]
Is it planned to be able to edit vehicle loadouts here? Or is there some other plan for that if there is one at all?

**Comment by Wyqer** [comment]
Editing vehicle loudouts is indeed something on our list.
Current thoughts are to tie it to the ammo trucks and not to a static object.
As soon as we've decided how we exactly implemented it, there will be a task for it which explains our approach.

**Comment by EvilSh4d0w** [comment]
i think you'll still keep the repair / ammunition and fuel trucks and the Huron containers. there it would be good if you manage to refill them with your own resources we've had it partly already that we had to refill them what doesn't work and then needed 10 of those things and then stand around (use of ACE fueling and ammunition / load configuration system)
