### ISSUE TITLE
Universal Unit Preset Template pt. 2

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#539]
### Short Summary
Next part on #522 

### Description
With the finished first draft of the universal army presets, which can be used as friendly or enemy side, we now have to adjust all present code concerning variable references and handling to the new variable names. And it's also possible that we need to tweak the draft accordingly to circumstances we haven't thought of yet.
This task will be done more or less independently on each module by the original module developer.
After this part, we would highly appreciate contributions of army presets from the community. 🙂 

### Sub-Tasks
- [x] Adjust preset initialization, mod filtering and variable publishing to clients
- [x] Common module adjustment
- [x] Core module adjustment
- [x] ~~Respawn module adjustment~~
- [x] Build module adjustment
- [x] Garrison module adjustment
