### ISSUE TITLE
Garrison module pt. 2

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#540]
### Short Summary
Next part of #511 

### Description
With the basic functionality of spawning/despawning and persistence of garrisons the main feature of fighting against enemy AI is implemented.
Now we need some more API function for adding, removing, etc. values from/to a garrison.
Also the "change preset during running server without restart" feature needs the adjustment to reinitialize the preset file. This wasn't part of the #537 PR, as the initPresets needs an overhaul due to the new preset template. Therefore the call of that function wasn't implemented in the garrison reinitialization functionality yet.
Also the "rarely flying tanks/vehicles on spawn" (brought to you by Red Bull) issue from #520 is still open, as mentioned in #537 and should be adressed in this task.

Management of the garrison of captured sectors with a dialog to add/remove vehicles/soldiers for players (basically "friendly garrison handling") would be the content of a 3rd part for this module.

### Sub-Tasks
- [x] Add functions which can be used to manipulate and read data in specific garrisons
- [x] Implement last adjustments for the "on the fly" garrison reinitialization after a preset change
- [x] Improve vehicle spawn in urban areas
