### ISSUE TITLE
Permission system Part 1

### ISSUE THREAD

**Issue by Dubjunk** [KillahPotatoes/KP-Liberation#541]
### Short Summary
As an admin I wanna be able to control the player permissions, like vehicle usage or the build menu.

### Description
We want to provide a permission system, which can be controlled by the commander and admin.
There will be an dialog with a list of every player that has joined the mission since the last wipe.

the permission system will influence:
- Light vehicles
- Heavy vehicles
- Helicopters
- Planes
- Support vehicles
- Build
- Recycle
- Production
- Logistic
- Commander
- Sub-commander

### Sub-Tasks
- [x] Create `permission`module
- [x] Provide a permission dialog for admin and commander
- [x] Setup general functions
    - [x] Check specific permission
    - [x] Set permissions
- [ ] Implement it to the various modules

**Comment by EvilSh4d0w** [comment]
it is possible to link the right ones so that if I give player A right ones to use light vehicles and the right ones to build he can only build the vehicles released for him but not everything and player B to whom I give full brewing rights can build everything regardless of what he has for vehicle rights. Or would you think nothing of such a right system?

**Comment by Dubjunk** [comment]
The permission module is just a framework so everything is possible, but this feature is not planned to be provided as a "default feature".
