### ISSUE TITLE
Civilian reputation

### ISSUE THREAD

**Issue by veteran29** [KillahPotatoes/KP-Liberation#553]
### Short Summary
As a player I want civilians to react to my actions, either negativiely or positively, reputation system is needed for that.

### Description
Reputation value and adjustment functions for the civilian reputation, on which later modules will build upon (like resistance).
Moreover it should handle and record the destroyed buildings in sectors, maybe even save these states, so that we could implement possibilities to provide side missions to help the population with rebuilding, etc.

### Sub-Tasks
- [ ] Civilian reputation value
- [ ] Functions to influence the civilian reputation
- [ ] Handle destroyed buildings
- [ ] Evaluation of possibilities to save the state of destroyed buildings in sectors (thinking of possibilities for side missions to rebuild houses, etc.)

**Comment by Havoc302** [comment]
Would it be possible to add a side mission where you can deploy an aid station at a town to get some increased standing with the civilian populace at the cost of supplies and fuel, but it also increases the chance of an attack on that town from a battlegroup and increases your overall threat rating? 

I'd also like to see the civilians run away from gunfire, rather than towards my vehicle, they constantly end up run over by my stupid AI.

**Comment by Zeata** [comment]
when capturing a town, our reputation decreases because of "building being lost or destroyed" most of that damage is done by enemy forces use of rocket launchers and there is nothing we can do to get the reputation back up. 
My suggestion is to add some sort of mission to get the reputation back up or remove the decrease in reputation from destroyed buildings

**Comment by Wyqer** [comment]
This issue is not for the legacy (current stable) framework. Read the article about civilian reputation in the Wiki.
