### ISSUE TITLE
Logistic module pt. 2

### ISSUE THREAD

**Issue by Dubjunk** [KillahPotatoes/KP-Liberation#569]
### Short Summary
As a player I want to have a sensible place where I've access to logistical features like repair/rearm/refuel/salvage/etc., so that there are no global actions and weird civilian workshop buildings for these things anymore.

### Description
This will be the second part of this module and will contain some additions/changes/improvements.

Main content will be:
* Adjusted cratefiller
* Maybe some kind of logistic paradrop feature
* (AI logistic convois)

### Sub-Tasks
- [x] Implement KP Cratefiller with needed adjustements
- [x] Additions/changes/improvements
- [ ] Create AI Logistics dialog (this will maybe moved to an own task)
- [x] Implement resource module

**Comment by Dubjunk** [comment]
The camera function should be changed to avoid the spawn of functions.

Example from @veteran29 :

```sqf
private _fnc_cameraCircleAroundLoop = {
    params ["_list", "_camera", "_target", "_steps", ["_duration", 30, [0]], ["_step", 0, [0]], "_commitTime"];

    if (isNull _camera || {!camCommitted _camera}) exitWith {};

    if (_step isEqualTo 0) then {
        _commitTime = _duration / _steps;
    };

    _camera camSetPos ((_target getRelPos [15, _step * 10]) vectorAdd [0, 0, 5]);
    _camera camCommit _commitTime;

    _step = _step + 1;
    [_fnc_cameraCircleAroundLoop, _this, 0] call CBA_fnc_waitAndExecute;
};

[_ctrlVehicleList, _cam, _vehicle, 36, 30] call _fnc_cameraCircleAroundLoop;
```

**Comment by veteran29** [comment]
Just looking at my suggestion, the function should be global or it won't be seen by `CBA_fnc_waitAndExecute` callback.
