### ISSUE TITLE
Permission module additions

### ISSUE THREAD

**Issue by Dubjunk** [KillahPotatoes/KP-Liberation#571]
### Short Summary
As admin i wanna be able to control the permissions of players, to prevent abuse of several functionalities/vehicles.

### Description
There will be some more given permissions and maybe some little tweaks to the module.

### Sub-Tasks
- [x] Add `Build` permission
- [x] Add `Logistic Station` permission
- [x] Additions to the `registerPlayer` function

**Comment by tyl3r99** [comment]
I have a request that if it's possible to seperate the permissions building/buying assets? Not sure if it's too much of a headache what do you think?

**Comment by Dubjunk** [comment]
Everything is possible, but it could be a bunch of work. As we'll not integrate such things for default you'd need to do it on your own.

**Comment by tyl3r99** [comment]
Ahh okay thanks for the swift reply!



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
