### ISSUE TITLE
Garrison module pt3

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#573]
### Short Summary
Next part of #511 and #540

### Description
With the third part of the module I'm planning to implement the functions to handle blufor garrisons after players capture a sector. Depending on the time and progress it'll also contain a small dialog to manage the blufor garrison via adding/removing/transfer of units. If my spare time is not sufficient, the dialog will be added in a pt4.
Also there will be another iteration for the general vehicle spawning functions, as we're still not really happy with the way it behaves, its reliability concerning "boom" and we guess there could still be a small performance increase reached. We'll see how it goes.

### Sub-Tasks
- [x] Implement/Adjust functionalities to (un)garrison blufor units
- [x] Tweak general vehicle spawn function(s) according to discovered possibilities
- [x] (optional) Implement a first iteration for a "garrison management" dialog for the blufor commander to manage the garrisons of captured sectors.

**Comment by tyl3r99** [comment]
Quick question regarding the new friendly AI garrisons. 

Will they be virtual until x meters away? potentially helping with performance. 
or will they only spawn when under attack.

**Comment by Wyqer** [comment]
The garrison will be "virtually stored" and spawns automatically upon attacks.
With the full implemented dialog (scheduled for S12) you can (un)garrison units at captured sectors individually. So you could e.g. garrison a full squad of infantry which are near the sector and a tank. And later ungarrison the tank to send him via zeus to another sector and garrison the tank there, etc.
