### ISSUE TITLE
Enemy Commander pt2

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#574]
### Short Summary
Next part of #529 

### Description
This part will provide the foundations for the "decision making" of the enemy commander. So the target is to implement routines (maybe think about a FSM for this) to trigger certain enemy actions concerning reinforcing/transfer garrisons, like it was mentioned in pt1:

> This by moving vehicles/soldiers from one sector to another or by reinforcing them from his military bases (which could be considered as enemy forces spawn points)

Furthermore a first implementation of the mechanic, that the enemy won't directly know the positions of the players FOBs and may send out reconnaissance teams in the area where the players are progressing, to discover the FOB, so it would be a valid target for later counter attacks by the enemy commander. Until it's not discovered it shouldn't be a valid target. Maybe this could be some kind of "semi realistic" due to the fact that some maps are maybe not that big and FOBs might be built near to sectors. We need to test that after we've a basic mechanic for this idea.

**2019-06-09 - Edit**
Garrison reinforcement etc. will be moved to the next iteration.
This iteration is laying down the basic FSM, enemy patrols and likely the recon mission to get knowledge about player FOBs.

### Sub-Tasks
- [x] Implement/Research possible routine/FSM for a reliable and plausible "enemy reactions/decisions" mechanic
- [x] Implement patrols in enemy territory as function and in routine/FSM
- [x] ~~Implement "discover player FOBs" functionalities~~ Will be moved to next sprint
- [x] ~~Implement this mechanic in the routine/FSM~~ Will be moved to next sprint
