### ISSUE TITLE
Build System pt6

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#575]
### Short Summary
Next part of #523

### Description
In this part of the build system, we'll take care of the resource handling upon built. Ideally with a temporary functionality, that it just remove resources, if available but also build when not available. This due to the fact, that the production module isn't implemented yet, so there is no real income of resources at the moment. After the production module is done, this temporary "second route" will be removed.
Also it should be possible to remove/recycle buildings (not vehicles or units) via the build menu and add the resources to the storages of the corresponding FOB.
The both things above may need some additional QoL functions in the resources module, which will be added through this task if needed.

Also we've discorvered an issue with the dialog, that longer names of buildable objects may overflow the resource cost columns. This is something which should be taken care of by shorten the names if needed or rearrange the build dialog.

### Sub-Tasks
- [x] Implement resource handling upon build
- [ ] Implement remove/recycle functionality of buildings
    - [ ] Functionality which adds resources which are obtained through remove/recycle to the FOB storages
- [ ] Adjust the build menu dialog concerning the overflow issue
- [ ] Add build queue in right panel
