### ISSUE TITLE
Persistence Module

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#576]
### Short Summary
As Developer/Contributor I would like to have a possibility to just add objects to a save/load routine, so I don't have to implement an own one in each module which works with objects.

### Description
This module should handle all the saving/loading of objects in the campaign. In the old framework we had routines where one takes care of vehicles/units, one takes care of resource crates and storage contents, etc.
To eliminate this cluttering, we decided to implement a module which takes care of all this at one place and provides a kind of function/event handler framework to register objects to be handled via this module with specific and individual conditions (like in FOB area or similar).
This will also ensure that if there may be issues with placements after loading or something like that, that it's only one place to adjust it and not have the odd situation to adjust something in X amount of modules, as there is not only one module which spawns objects. Also tweaks concerning performance will be possible at one place.
This module will make it necessary to adjust some other modules (like the build menu which already save/load the FOB stuff) to use this module instead of own implementations. As this is kind of a "core functionality" for the mission, it'll be created on place 03 in the module hirarchy, so the current 03 and 04 modules needs to be incremented by one order number and therefore also the include references etc.

### Sub-Tasks
- [x] Implement a general object saving and loading functionality
- [x] Implement a functions or event handlers framework which can be utilized by every other module
    - [x] Move the current implementations of object save/load (like in the build module) to the persistence module handling
- [x] Rearrange the module order accordingly

**Comment by tyl3r99** [comment]
will vehicles be saved anywhere around the map?

**Comment by Wyqer** [comment]
Yes, that's the aim.

**Comment by tyl3r99** [comment]
Other than that will it be roughly the same as 0.963a? like fob area etc 
Sorry just clarifying 🥇

**Comment by Wyqer** [comment]
The aim is to make persistent not depending on fixed positions and ranges like FOB area etc.
