### ISSUE TITLE
Garrison module pt4

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#587]
### Short Summary
Next part of #511, #540 and #573 

### Description
As the foundation for the garrison dialog is finished, in this part it'll come to implement all the missing features/functions and finish the dialog. So the garrison module should have its full planned functionality basically finished.

### Sub-Tasks
- [x] Add ungarrison of light/heavy vehicles
- [x] Design "actions area" in the dialog for garrison of units
    - [x] Add functionality to garrison infantry
    - [x] Add functionality to garrison light/heavy vehicles
- [x] Fix issue that garrison vehicles aren't reinitialized upon preset change
