### ISSUE TITLE
Arsenal, Logistic, Permission codework finishing

### ISSUE THREAD

**Issue by Dubjunk** [KillahPotatoes/KP-Liberation#588]
### Short Summary
Code finishing of the Arsenal, Logistic and Permission module.

### Description
There are several changes and tweaks to do which will ensure that the modules are completely finished (until a possible code overhaul).

### Sub-Tasks
- [x] arsenal module finishing
- [x] logistic module finishing
- [x] permission module finishing
- [x] cratefiller module finishing

**Comment by Dubjunk** [comment]
There's a permission to access the cratefiller.
https://github.com/KillahPotatoes/KP-Liberation/blob/v0.97S12-588/Missionframework/modules/11_permission/fnc/fn_permission_postInit.sqf#L77
