### ISSUE TITLE
Resource production pt1

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#648]
### Short Summary
As a player I want to be able to produce resources at factories, so I can use them to build more troops, vehicles and buildings at my FOBs.

### Description
This will be the first **foundation** for the resource production. Basically it'll be very similar to the old framework from the "how it works", but will be most likely implemented via a FSM which takes care of the whole process. We don't expect that it'll be fully usable (completed) after this first part, but could be enough for a very basic and general gameplay aspect, so you don't need to spawn the resources anymore via debug console.

### Sub-Tasks
- [ ] Create dialog for factory management
- [ ] Add ability to build a storage at factories
- [ ] Add data structure for saving of the production
- [ ] Implement FSM to take care of the production cycles and resource spawning

**Comment by mwpowellhtx** [comment]
Assessing distance, from _current state_, to _ready up_ state... Given `22 prod` does not even exist yet, for instance, no apparent log UI, ability to manage site production, etc, perhaps _Done_ was a bot that changed that status? Have I got that accurate? I've got other questions, but specifically this. Please advise. Thank you... @Wyqer @veteran29

**Comment by Dubjunk** [comment]
The status "done" was set via automation (as you can see) because the issue got closed and moved to Icebox.
