### ISSUE TITLE
Liberation HUD implementation

### ISSUE THREAD

**Issue by Dubjunk** [KillahPotatoes/KP-Liberation#682]
### Short Summary
As a player I want to be able to get an overview of some liberation related informations, like CivRep, resources and so on.

### Description
This task will integrate the HUD of the old liberation into the new framework, with some changes.
The HUD style will be overhauled to match the new dialog design and it will be possible to add more informations to it (similar to the logistic menu).
Also there will be the possibility to decide if the HUD is shown or not via an action.

### Sub-Tasks
- [ ] Basic HUD framework
- [ ] Pre defined informations
    - [ ] CivRep
    - [ ] Enemy alert level
    - [ ] Intel
    - [ ] FOB resources
