### ISSUE TITLE
Arsenal additions

### ISSUE THREAD

**Issue by Dubjunk** [KillahPotatoes/KP-Liberation#684]
### Short Summary
As a player i want to be able to access the arsenal during the running mission, so that i can get my job on the battlefield done.

### Description
Some additions to #526 

### Sub-Tasks
- [ ] Deeper ACE integration
    - [ ] Load ACE loadouts instead of vanilla loadouts
    - [ ] Switch the default loadout when ACE is active
