### ISSUE TITLE
Check and organize current arsenal presets

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#749]
### Short Summary
As server admin I would like to have updated and nicely organized predefined arsenal presets, so that I can more easily adjust existing and/or create new arsenal presets.

### Description
The arsenal presets in the current stable Liberation releases are mostly many years old and not sorted or otherwise organized beside of the general category of the classnames.
They should be checked, if all classnames are still correct and if not some new classnames are added to supported mods.
Furthermore a more organized file like the [Unsung arsenal preset](https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/arsenal_presets/unsung.sqf) would be nice.
Best case scenario would be, if every classname has the ingame name as comment added, like it's already the case in the faction presets like the [custom.sqf](https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/presets/blufor/custom.sqf).

### Sub-Tasks
- [x] Recheck the contents of all currently available presets
- [x] Add a reusable and updated list of ACE, ACRE and TFAR items to all presets
    - [x] Check ACE classnames
    - [x] Check ACRE classnames
    - [x] Check TFAR classnames
    - [ ] Add these lists to all presets were sensible (e.g. Unsung shouldn't get modern radios)
- [x] Remove unused `XYZ_ACE` and `XYZ_ACE_ACRE` presets
- [x] Adjust/Update the arsenal preset list in `kp_liberation_config.sqf`
